### PR TITLE
Gun class refactoring

### PR DESCRIPTION
**Pull request by Fatalan**
Hi! Didn't have an opportunity to test this out 'cause you didn't provide full VS project with all the resources so please consider testing before merging

### CODE REVIEW

**Comment by Lonewolf239** [comment]
If you want to test the game, you can download its current installer from the website: https://base-escape.ru/downloads/Setup_Mini_Games.exe

**Comment by Fatalan** [comment]
> If you want to test the game, you can download its current installer from the website: https://base-escape.ru/downloads/Setup_Mini_Games.exe

I wanted to test the changes I made to the code, not the game itself. Installer is pre-built so it won't do and the source code you uploaded to your GitHub repository doesn't contain **.sln** file nor **Resources.resx** file so building the app would be problematic 'cause it'd require adding all the resources and setting up all the dependencies like **NAudio** and **SharpDX** by hand

**Comment by Lonewolf239** [comment]
I understood you. I added the .sln file and Properties

**Comment by Fatalan** [comment]
I also forgot to mention that you should include **.csproj** file(s) which contain information about the files included in the project, assemblies used in that project, project GUID and project version etc.

**Comment by Lonewolf239** [comment]
Did it

**Comment by Fatalan** [comment]
And **App.config** =)

**Comment by Lonewolf239** [comment]
Did it

**Comment by Lonewolf239** [comment]
pls check tg

**Pull request closed without merging**
